export const LOGIN_ROUTE:string = '/login';
export const HOME_ROUTE:string = '/';
export const SECTION_PAGE_ROUTE:string = '/section';
export const SECTION_PAGE_ADMIN_ROUTE:string = '/admin/section';
export const TEST_PAGE_ROUTE:string = '/test';
export const TEST_PAGE_ADMIN_ROUTE:string = '/admin/test';
export const COURSE_PAGE_ROUTE:string = '/course';
export const COURSES_PAGE_ROUTE:string = '/courses';
export const PROFILE_EDIT_PAGE_ROUTE:string = '/profileEdit';
export const COURSE_PAGE_ADMIN_ROUTE:string = '/admin/course';
export const NOT_FOUND_ROUTE: string = '/not_found'